[build]
  base = "client"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  
[build.environment]
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"