import './globals.css'
import { Onest } from 'next/font/google'

const onest = Onest({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-onest",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={onest.className}>{children}</body>
    </html>
  )
}
