import NavBar from './components/NavBar'
import styles from './page.module.css'
import EventCard from './components/events/EventCard'
import EventCarousel from './components/events/EventCarousel'

export default function Home() {
  const testEvents = [
    {
      id: 1,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Sleepless Collective Fall Auditions",
      eventOwner: "UCSD Giving",
      eventDate: "Aug 20, 2025",
      eventTime: "6:00 PM",
      eventLocation: "PC Ballroom East",
      eventDescription: "An evening of performances and fundraising for student orgs.",
      eventTags: ["Fundraiser", "Public", "Free"],
    },
    {
      id: 2,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Sunset Yoga",
      eventOrganization: "Health & Wellness Club",
      eventDate: "Aug 22, 2025",
      eventTime: "5:30 PM",
      eventLocation: "Warren Lawn",
      eventDescription: "Wind down with a free yoga class during golden hour.",
      eventTags: ["Free", "Wellness", "Outdoor"],
    },
    {
      id: 3,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Hack for Impact",
      eventOrganization: "TritonHacks",
      eventDate: "Sep 01, 2025",
      eventTime: "9:00 AM",
      eventLocation: "CSE Building",
      eventDescription: "24-hour hackathon focused on social good and non-profits.",
      eventTags: ["Hackathon", "Tech", "Fundraiser"],
    },/*
    {
      id: 4,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Cultural Night",
      eventOrganization: "Kaibigang Pilipino",
      eventDate: "Sep 10, 2025",
      eventTime: "7:00 PM",
      eventLocation: "Mandeville Auditorium",
      eventDescription: "Annual showcase of cultural dance and performance.",
      eventTags: ["Fundraiser", "Performance", "Public"],
    },
    {
      id: 5,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "General Body Meeting",
      eventOrganization: "Women in Computing",
      eventDate: "Sep 12, 2025",
      eventTime: "6:00 PM",
      eventLocation: "CSE 1202",
      eventDescription: "Get to know the org and upcoming opportunities.",
      eventTags: ["GBM", "Tech", "Free"],
    },
    {
      id: 6,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Food for Finals",
      eventOrganization: "AS Programming",
      eventDate: "Sep 18, 2025",
      eventTime: "12:00 PM",
      eventLocation: "Library Walk",
      eventDescription: "Grab free snacks and energy drinks before finals week.",
      eventTags: ["Free", "Food", "Stress Relief"],
    },
    {
      id: 7,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Startup Showcase",
      eventOrganization: "The Basement",
      eventDate: "Sep 22, 2025",
      eventTime: "3:00 PM",
      eventLocation: "Design Lab",
      eventDescription: "Pitch your startup ideas and network with VCs.",
      eventTags: ["Pitch", "Tech", "Entrepreneurship"],
    },
    {
      id: 8,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "International Potluck",
      eventOrganization: "iHouse",
      eventDate: "Sep 24, 2025",
      eventTime: "6:30 PM",
      eventLocation: "ERC Lawn",
      eventDescription: "Bring a dish from your culture and make new friends!",
      eventTags: ["Cultural", "Food", "Free"],
    },
    {
      id: 9,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Eco-Clean Beach Day",
      eventOrganization: "Green Tritons",
      eventDate: "Sep 28, 2025",
      eventTime: "9:00 AM",
      eventLocation: "La Jolla Shores",
      eventDescription: "Volunteer to clean the beach and protect the coast.",
      eventTags: ["Volunteer", "Sustainability", "Outdoor"],
    },
    {
      id: 10,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Late Night Laughs",
      eventOrganization: "Campus Comedy Club",
      eventDate: "Sep 30, 2025",
      eventTime: "8:00 PM",
      eventLocation: "PC Theater",
      eventDescription: "Stand-up comedy night featuring local student talent.",
      eventTags: ["Entertainment", "Free", "Comedy"],
    },
    {
      id: 11,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Game Night",
      eventOrganization: "Revelle Res Life",
      eventDate: "Oct 1, 2025",
      eventTime: "7:00 PM",
      eventLocation: "Revelle Commons",
      eventDescription: "Join us for board games, card games, and snacks.",
      eventTags: ["Free", "Games", "Community"],
    },
    {
      id: 12,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Research Expo",
      eventOrganization: "Undergrad Research Hub",
      eventDate: "Oct 3, 2025",
      eventTime: "2:00 PM",
      eventLocation: "Price Center",
      eventDescription: "Learn about student research and how to get involved.",
      eventTags: ["Academic", "STEM", "Opportunity"],
    },
    {
      id: 13,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Kpop Random Play Dance",
      eventOrganization: "Kpop Club",
      eventDate: "Oct 5, 2025",
      eventTime: "4:00 PM",
      eventLocation: "Library Walk",
      eventDescription: "Dance along with your favorite Kpop hits in a fun mixer!",
      eventTags: ["Dance", "Music", "Free"],
    },
    {
      id: 14,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Meditation Circle",
      eventOrganization: "Triton Mindfulness",
      eventDate: "Oct 6, 2025",
      eventTime: "10:00 AM",
      eventLocation: "Wellness Room",
      eventDescription: "Start your morning with guided meditation and reflection.",
      eventTags: ["Wellness", "Free", "Mental Health"],
    },
    {
      id: 15,
      eventCover: "https://via.placeholder.com/400x200",
      eventName: "Women in Leadership Panel",
      eventOrganization: "Triton Women",
      eventDate: "Oct 10, 2025",
      eventTime: "5:00 PM",
      eventLocation: "Center Hall",
      eventDescription: "Hear from women leaders and network with peers.",
      eventTags: ["Leadership", "Career", "Panel"],
    },*/
  ];

  return (
    <>
      <EventCarousel category="Free Food" events={testEvents} />
    </>
  );
}
