import NavBar from './components/NavBar'
import styles from './page.module.css'
import EventCard from './components/events/EventCard'
import EventCarousel from './components/events/EventCarousel'

export default function Home() {
  const testEvents = [
    {
      id: 1,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Fall Auditions",
      eventOwner: "Sleepless Collective",
      eventDate: "2025-08-20T18:00:00",
      eventLocation: "Gilman 5th Floor",
      eventDescription: "An evening of performances and fundraising for student orgs.",
      eventTags: ["Fundraiser", "Public", "Free"],
    },
    {
      id: 2,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Sunset Yoga",
      eventOwner: "Health & Wellness Club",
      eventDate: "2025-08-22T17:30:00",
      eventLocation: "Warren Lawn",
      eventDescription: "Wind down with a free yoga class during golden hour.",
      eventTags: ["Free", "Wellness", "Outdoor"],
    },
    {
      id: 3,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Hack for Impact",
      eventOwner: "TritonHacks",
      eventDate: "2025-09-01T09:00:00",
      eventLocation: "CSE Building",
      eventDescription: "24-hour hackathon focused on social good and non-profits.",
      eventTags: ["Hackathon", "Tech", "Fundraiser"],
    },
    {
      id: 4,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Cultural Night",
      eventOwner: "Kaibigang Pilipino",
      eventDate: "2025-09-10T19:00:00",
      eventLocation: "Mandeville Auditorium",
      eventDescription: "Annual showcase of cultural dance and performance.",
      eventTags: ["Fundraiser", "Performance", "Public"],
    },
    {
      id: 5,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "General Body Meeting",
      eventOwner: "Women in Computing",
      eventDate: "2025-09-12T18:00:00",
      eventLocation: "CSE 1202",
      eventDescription: "Get to know the org and upcoming opportunities.",
      eventTags: ["GBM", "Tech", "Free"],
    },
    {
      id: 6,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Food for Finals",
      eventOwner: "AS Programming",
      eventDate: "2025-09-18T12:00:00",
      eventLocation: "Library Walk",
      eventDescription: "Grab free snacks and energy drinks before finals week.",
      eventTags: ["Free", "Food", "Stress Relief"],
    },
    {
      id: 7,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Startup Showcase",
      eventOwner: "The Basement",
      eventDate: "2025-09-22T15:00:00",
      eventLocation: "Design Lab",
      eventDescription: "Pitch your startup ideas and network with VCs.",
      eventTags: ["Pitch", "Tech", "Entrepreneurship"],
    },
    {
      id: 8,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "International Potluck",
      eventOwner: "iHouse",
      eventDate: "2025-09-24T18:30:00",
      eventLocation: "ERC Lawn",
      eventDescription: "Bring a dish from your culture and make new friends!",
      eventTags: ["Cultural", "Food", "Free"],
    },
    {
      id: 9,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Eco-Clean Beach Day",
      eventOwner: "Green Tritons",
      eventDate: "2025-09-28T09:00:00",
      eventLocation: "La Jolla Shores",
      eventDescription: "Volunteer to clean the beach and protect the coast.",
      eventTags: ["Volunteer", "Sustainability", "Outdoor"],
    },
    {
      id: 10,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Late Night Laughs",
      eventOwner: "Campus Comedy Club",
      eventDate: "2025-09-30T20:00:00",
      eventLocation: "PC Theater",
      eventDescription: "Stand-up comedy night featuring local student talent.",
      eventTags: ["Entertainment", "Free", "Comedy"],
    },
    {
      id: 11,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Game Night",
      eventOwner: "Revelle Res Life",
      eventDate: "2025-10-01T19:00:00",
      eventLocation: "Revelle Commons",
      eventDescription: "Join us for board games, card games, and snacks.",
      eventTags: ["Free", "Games", "Community"],
    },
    {
      id: 12,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Research Expo",
      eventOwner: "Undergrad Research Hub",
      eventDate: "2025-10-03T14:00:00",
      eventLocation: "Price Center",
      eventDescription: "Learn about student research and how to get involved.",
      eventTags: ["Academic", "STEM", "Opportunity"],
    },
    {
      id: 13,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Kpop Random Play Dance",
      eventOwner: "Kpop Club",
      eventDate: "2025-10-05T16:00:00",
      eventLocation: "Library Walk",
      eventDescription: "Dance along with your favorite Kpop hits in a fun mixer!",
      eventTags: ["Dance", "Music", "Free"],
    },
    {
      id: 14,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Meditation Circle",
      eventOwner: "Triton Mindfulness",
      eventDate: "2025-10-06T10:00:00",
      eventLocation: "Wellness Room",
      eventDescription: "Start your morning with guided meditation and reflection.",
      eventTags: ["Wellness", "Free", "Mental Health"],
    },
    {
      id: 15,
      eventCover: "https://via.placeholder.com/400x200",
      eventTitle: "Women in Leadership Panel",
      eventOwner: "Triton Women",
      eventDate: "2025-10-10T17:00:00",
      eventLocation: "Center Hall",
      eventDescription: "Hear from women leaders and network with peers.",
      eventTags: ["Leadership", "Career", "Panel"],
    },
  ];


  return (
    <>
      <EventCarousel category="Free Food" events={testEvents} />
    </>
  );
}
